+ Карточка персонажа
karvalolka/luminary pull request #10
Opened 2024-10-11 17:20 UTC by karvalolka

2024-10-11 17:31 UTC, kovdmit commented on resources/views/profile/index.blade.php
> +                                            <p>{{$char->race->name}}</br></p>
Эта конструкция используется несколько раз в коде ниже. Предлагаю создать для персонажа метод получения названия расы, фракции, класса.

2024-10-11 17:31 UTC, kovdmit commented on resources/views/profile/index.blade.php
> +                                            <p>{{$char->grade->name}}</br></p>
См. Коммент выше

2024-10-11 17:31 UTC, kovdmit commented on resources/views/profile/index.blade.php
> +                                            <p>{{$char->fraction->name}}</br></p>
См коммент выше

2024-10-11 17:31 UTC, kovdmit commented on resources/views/profile/show.blade.php
> +                            <td>{{ $char->race->name }}</td>
См коммент выше

2024-10-11 17:31 UTC, kovdmit commented on resources/views/profile/show.blade.php
> +                            <td>{{ $char->grade->name }}</td>
См коммент выше

2024-10-11 17:31 UTC, kovdmit commented on resources/views/profile/show.blade.php
> +                            <td>{{ $char->fraction->name }}</td>
См коммент выше

2024-10-15 06:22 UTC, kovdmit requested changes

2024-10-15 06:22 UTC, kovdmit commented on app/Http/Controllers/Admin/Char/StoreCharController.php
> +        if ($characterCount >= 2) {
Необходимо избавиться от магических числел

2024-10-15 06:22 UTC, kovdmit commented on app/Http/Controllers/Personal/Char/StoreCharController.php
> +        $characterCount = Char::where('user_id', $data['user_id'])->count();
Дублируется бизнес-логика.

2024-10-15 06:22 UTC, kovdmit commented on app/Models/Weapon.php
> +    public function chars()
Одно оружие может быть у нескольких персонажей?

2024-10-15 06:22 UTC, kovdmit commented on database/migrations/2024_10_14_172403_add_column_weapon_id_in_chars_table.php
> +        Schema::create('chars_new', function (Blueprint $table) {
Что тут происходит вообще?

2024-10-15 06:22 UTC, kovdmit commented on resources/views/main/index.blade.php
> +                                                <td>{{$char->attack_power + ($characterWeapons[$char->id]->power ?? 0)}}</td>
Надо вынести в отдельный метод

2024-10-15 06:22 UTC, kovdmit commented on resources/views/profile/show.blade.php
> +                                @if ($weapon)
Вынести в отдельный метод

2024-10-15 06:22 UTC, kovdmit commented on resources/views/profile/show.blade.php
> +                            <td>{{ $char->weapon ? $char->weapon->name : 'Нет оружия' }}</td>
Вынести в отдельный метод

2024-10-15 06:22 UTC, kovdmit commented on app/Http/Controllers/Admin/Char/StoreCharController.php
>      {
В очередной раз повторяю: не надо коммитить новую разработку в существующий PR.
Если ты скидываешь PR на ревью, а я написал замечания, то надо их исправить, потом слить ветки, а потом только создавать новый PR и пушить новые изменения.
Либо вести разработку каждой фичи в отдельной ветке.

2024-10-15 16:48 UTC, karvalolka commented on database/migrations/2024_10_14_172403_add_column_weapon_id_in_chars_table.php
> +        Schema::create('chars_new', function (Blueprint $table) {
особенность sqlite в том что в таблицах нельзя  удалять ключи. Создаётся новая таблица, импортируются данные из старой, старая удаляется и переименовывается

2024-10-15 18:04 UTC, kovdmit commented on database/migrations/2024_10_14_172403_add_column_weapon_id_in_chars_table.php
> +        Schema::create('chars_new', function (Blueprint $table) {
Это ответ не на мой вопрос.

2024-10-17 15:45 UTC, karvalolka commented on database/migrations/2024_10_14_172403_add_column_weapon_id_in_chars_table.php
> +        Schema::create('chars_new', function (Blueprint $table) {
создаётся таблица с новым неймом и старыми столбцами.
в неё сохраняются данные из действующей таблицы,
старая таблица удаляется, новая ренеймится

2024-10-19 10:56 UTC, merged