Develop
karvalolka/luminary pull request #3
Opened 2024-09-04 18:09 UTC by karvalolka

2024-09-05 05:40 UTC, kovdmit requested changes

2024-09-05 05:40 UTC, kovdmit commented on database/migrations/2024_09_04_160226_create_chars_table.php
> +            $table->unsignedTinyInteger('level');
В ТЗ не было поля уровень. Было только опыт. Ну ладно, пусть уже остаётся

2024-09-05 05:40 UTC, kovdmit commented on database/migrations/2024_09_04_160226_create_chars_table.php
> +            $table->unsignedInteger('xp');
Не критично: Windows XP?) Опыт обозначают либо experience либо exp

2024-09-05 05:40 UTC, kovdmit commented on database/migrations/2024_09_04_160356_create_inventories_table.php
> +            $table->text('loot');
Для чего это поле?

2024-09-05 05:40 UTC, kovdmit commented on database/migrations/2024_09_04_160356_create_inventories_table.php
> +    }
А как же 5 ячеек для инвентаря?

2024-09-05 05:40 UTC, kovdmit commented on database/migrations/2024_09_04_173925_create_armors_table.php
> +            $table->unsignedSmallInteger('def');
Неочевидное наименование. Используй value например

2024-09-05 05:40 UTC, kovdmit commented on database/migrations/2024_09_04_173952_create_weapons_table.php
> +            $table->unsignedSmallInteger('attack');
Неочевидное наименование

2024-09-05 05:40 UTC, kovdmit commented on database/migrations/2024_09_04_173952_create_weapons_table.php
> +            $table->foreignId('protection_area_id')->constrained()->onDelete('cascade');
Как область защиты связана с оружием?

2024-09-05 05:40 UTC, kovdmit commented on app/Models/Char.php
> +}
Нет метода для получения класса

2024-09-05 05:40 UTC, kovdmit commented on app/Models/Inventory.php
> +}
Там шо то было про 5 ячеек

2024-09-05 05:40 UTC, kovdmit commented on app/Models/Weapon.php
> +    public function protectionArea()
Никак не могу понять, как оружие связано с областью защиты))

2024-09-05 14:26 UTC, karvalolka commented on database/migrations/2024_09_04_160226_create_chars_table.php
> +            $table->unsignedTinyInteger('level');
я изначально подумал, что ты написал опыт это значит уровень

2024-09-05 14:28 UTC, karvalolka commented on database/migrations/2024_09_04_160356_create_inventories_table.php
> +            $table->text('loot');
для золота

2024-09-05 14:29 UTC, karvalolka commented on database/migrations/2024_09_04_173925_create_armors_table.php
> +            $table->unsignedSmallInteger('def');
где

2024-09-05 14:29 UTC, karvalolka commented on database/migrations/2024_09_04_173952_create_weapons_table.php
> +            $table->unsignedSmallInteger('attack');
где

2024-09-05 17:21 UTC, kovdmit commented on database/migrations/2024_09_04_160226_create_chars_table.php
> +            $table->unsignedTinyInteger('level');
Лвл по сути можно динамически вычислять на основе опыта. Например если опыт, скажем = 13579, то 13 лвл. Чё то такое

2024-09-05 17:21 UTC, kovdmit commented on database/migrations/2024_09_04_173925_create_armors_table.php
> +            $table->unsignedSmallInteger('def');
def

2024-09-05 17:22 UTC, kovdmit commented on database/migrations/2024_09_04_173952_create_weapons_table.php
> +            $table->unsignedSmallInteger('attack');
Attack

2024-09-07 17:48 UTC, kovdmit requested changes

2024-09-07 17:48 UTC, kovdmit commented on app/Models/Char.php
> +        return $this->hasMany(Inventory::class);
У персонажа может быть много инвентарей?

2024-09-07 17:48 UTC, kovdmit commented on app/Models/Inventory.php
> +        if ($this->slots()->count() < 5) {
Плохая идея использовать "магические числа".

2024-09-07 17:48 UTC, kovdmit commented on app/Models/Inventory.php
> +            $this->slots()->create(['item' => $item]);
Я конечно не ларавельщик, но Шо то я не думаю, что у тебя получится так добавить предмет в инвентарь. 

Метод slots вернёт тебе коллекцию имеющихся слотов. И у этой коллекции вряд ли есть метод create.

Если я прав, Можешь оставить реализацию на дальнейшую разработку за рамками данного PR. Но тогда для этого удали этот метод.

Если не прав, то сори, я путхонист, у меня лапки

2024-09-07 17:48 UTC, kovdmit commented on app/Models/Inventory.php
> +    public function updateGold($amount)
Из названия метода непонятно, что он будет именно складывать старое значение с новым, а не просто перезаписывать старое

2024-09-07 17:48 UTC, kovdmit commented on database/migrations/2024_09_04_160226_create_chars_table.php
> +            $table->unsignedSmallInteger('attack');
Допиши плиз attack_power,  раз уж пошла такая пьянка

2024-09-07 17:48 UTC, kovdmit commented on database/migrations/2024_09_04_160226_create_chars_table.php
> +            $table->unsignedSmallInteger('def');
Тоже

2024-09-07 17:48 UTC, kovdmit commented on database/migrations/2024_09_07_170013_create_inventory_slots_table.php
> +            $table->string('item')->nullable();
Вот непонятно почему строка. Тут же должна быть ссылка на шмот.

2024-09-07 18:27 UTC, karvalolka commented on app/Models/Inventory.php
> +            $this->slots()->create(['item' => $item]);
"Друг" говорит, что должно работать, предлагаю уже на практике в будущем проверить

2024-09-08 07:42 UTC, kovdmit requested changes

2024-09-08 07:42 UTC, kovdmit commented on app/Models/Inventory.php
> +    public function changeGold($amount)
Ни "update", ни "change" не указывает на то, что передаваемое значение будет складываться со старым. 

Предлагаю использовать что-то вроде глагола "увеличить" или "сложить".

2024-09-08 07:44 UTC, kovdmit commented on app/Models/Inventory.php
> +            $this->slots()->create(['item' => $item]);
Принято

2024-09-11 16:00 UTC, merged

2024-10-06 21:05 UTC, gotyefrid commented on app/Models/Char.php
> +        return $this->hasMany(Inventory::class);
))инвентарь твой и инвентарь квестов - как в пв)))